# Generated by Django 5.2.1 on 2025-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='created',
            field=models.TimeField(auto_now=True),
        ),
    ]
