# Generated by Django 5.2.1 on 2025-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imge',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
