# Generated by Django 5.2.1 on 2025-05-21 20:27

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_imge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imge',
            field=models.ImageField(storage=products.models.MediaStorage(), upload_to='product/%Y/%m/%d'),
        ),
    ]
